---
# tasks file for ansible-role-folder-security

- name: "Create scripts directory under root homedir, if it does not exist"
  ansible.builtin.file:
    path: "/root/scripts/"
    state: directory

- name: "Deploy homedir permission script"
  ansible.builtin.template:
    src: homedir.j2
    dest: /root/scripts/homedir-permissions.sh
    owner: root
    group: root
    mode: '0750'

- name: "Run script to set mode 0750 on All Interactive User Home Directories"
  ansible.builtin.command: "./homedir-permissions.sh"
  args:
    chdir: "/root/scripts/"
